### ISSUE TITLE
Connection to server got closed. Server will not be restarted.

### ISSUE THREAD

**Issue by ghost** [microsoft/pgtoolsservice#251] opened 2020-07-09 00:04 UTC
On my Ubuntu 2004, this error is present.

This occurs when I am installing extensions (Admin Tools and PostgresSQL)

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/usr/local/lib/python3.6/dist-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "pgsqltoolsservice/pgtoolsservice_main.py", line 11, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ptvsd/__init__.py", line 17, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ptvsd/attach_server.py", line 35, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ptvsd/visualstudio_py_debugger.py", line 24, in <module>
  File "/usr/lib/python3.6/ctypes/__init__.py", line 7, in <module>
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
[Error - 19:59:23] Connection to server got closed. Server will not be restarted.

**Comment by nerfpops** [comment] 2020-07-12 14:54
Same error here with Ubuntu 20.04 and Python 3.8. Fixed by installing some packages, creating symlinks for python and libffi:

sudo -H pip3 install cx_freeze
sudo -H pip3 install ptvsd
sudo ln -s /usr/local/lib/python3.8/ /usr/local/lib/python3.6
sudo ln -s /usr/lib/python3.8 /usr/lib/python3.6
sudo ln -s /usr/lib/x86_64-linux-gnu/libffi.so.7 /usr/lib/x86_64-linux-gnu/libffi.so.6

**Comment by ediano** [comment] 2020-08-27 15:55
I managed to solve the problem in another way, in Ubuntu 20.04 and did a **sudo apt install -y libffi6**, then I made the connection formally.

Detail: I'm using Postgres in a Docker container, and the Azure Data Studio App with the Postgress extension.

**Comment by spapadim** [comment] 2020-12-31 17:46
> I managed to solve the problem in another way, in Ubuntu 20.04 and did a **sudo apt install -y libffi6**, then I made the connection formally.
> 
> Detail: I'm using Postgres in a Docker container, and the Azure Data Studio App with the Postgress extension.

Which apt repo do you use for libffi6 (focal repos only have libffi7)?  E.g., what does `apt policy libffi6` output? Thx!

Can't figure out why libffi dependency isn't vendorized. Everything else (including all of Python 3.6---well, almost all ;) ) seems to be.. oh well.

**Comment by spapadim** [comment] 2020-12-31 18:05
Ah, answering myself: likely a [cx_freeze](https://github.com/marcelotduarte/cx_Freeze) issue (there is a *vaguely*/*superficially* [similar issue for libffi on Windows](https://github.com/marcelotduarte/cx_Freeze/issues/596), but nothing for Unixen). 

Anyway, I have no time/desire to investigate and determine whether this should issue be pushed upstream (or whether it can be simply fixed by tweaking `include_files` in `setup.py` in this repo), but perhaps someone else reading this in the future might...

I'll kludge around it, just like everybody else for now. :)

**Comment by ediano** [comment] 2021-01-01 14:29
> Ah, answering myself: likely a [cx_freeze](https://github.com/marcelotduarte/cx_Freeze) issue (there is a _vaguely_/_superficially_ [similar issue for libffi on Windows](https://github.com/marcelotduarte/cx_Freeze/issues/596), but nothing for Unixen).
> 
> Anyway, I have no time/desire to investigate and determine whether this should issue be pushed upstream (or whether it should be fixed here, by tweaking `include_files` in `setup.py`), but perhaps someone else reading this in the future might...
> 
> I'll kludge around it, just like everybody else for now. :)

Due to the problems I faced after a while, I started using Beekeeper Studio, it is serving me very well.

Official website: https://www.beekeeperstudio.io/

**Comment by sgryphon** [comment] 2021-08-25 05:25
Appears to be a duplicate of https://github.com/microsoft/pgtoolsservice/issues/218 and should be closed.

They have the same error, a dialog that pops up on start and says "ImportError: libffi.so.6: cannot open shared object file: No such file or directory", then an error reported in the output section:

```
"It seems the debugger cannot resolve /opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/posixpath.py
This may make the debugger miss breakpoints in the standard library.
Related bug: https://bugs.python.org/issue1180193
... a stack trace ...
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
[Error - 12:57:17 PM] Connection to server got closed. Server will not be restarted."
```

The important bit is the missing "libffi.so.6"

There are many other duplicates (that should probably be closed as well)

https://github.com/microsoft/pgtoolsservice/issues/239
https://github.com/microsoft/pgtoolsservice/issues/251
https://github.com/microsoft/pgtoolsservice/issues/275
https://github.com/microsoft/pgtoolsservice/issues/279
https://github.com/microsoft/pgtoolsservice/issues/280
https://github.com/microsoft/pgtoolsservice/issues/282
https://github.com/microsoft/pgtoolsservice/issues/283

**Work around:**

So far, the workaround for some systems linking libffi.so.6 to version 7 seems to work:
 
```
sudo ln -s libffi.so.7 /usr/lib/x86_64-linux-gnu/libffi.so.6
```

The workaround does not work if you only have version 8, e.g. Ubuntu 20.10 -- it gets past the first error but then just fails. You can check which version you have via:

```
ls -la /usr/lib/x86_64-linux-gnu/libffi*
```

The other workaround is to directly install the version 6 libraries directly:

```
curl -o libffi6_3.2.1-8_amd64.deb http://mirrors.kernel.org/ubuntu/pool/main/libf/libffi/libffi6_3.2.1-8_amd64.deb
sudo apt install ./libffi6_3.2.1-8_amd64.deb
```

**Comment by nasc17** [comment] 2023-07-07 18:09
Issue has been addressed in our unstable release of PostgreSQL extension v0.4.2 using pgtoolsservice v1.8.0. We would appreciate your verification that it has been handled appropriately.

**Closed by nasc17** 2023-07-07 18:09 UTC
