### ISSUE TITLE
Linux (Ubuntu based) "PG SQL Tools Service component quit unexpectedly.

### ISSUE THREAD

**Issue by schoening** [microsoft/pgtoolsservice#275] opened 2020-09-07 12:04 UTC
This *might* be related to [154](https://github.com/microsoft/azuredatastudio-postgresql/issues/154) 
I have libffi7 (libff6 doesn't even exist in the apt-cache)

![image](https://user-images.githubusercontent.com/1976060/92385728-ab11d780-f112-11ea-9718-c2a83f969dd0.png)

**Comment by schoening** [comment] 2020-09-07 12:30
Linking libffi7 as libffi6 solved the problem for now. Not ideal tho...

https://stackoverflow.com/questions/61875869/ubuntu-20-04-upgrade-python-missing-libffi-so-6

**Comment by DiomedesDominguez** [comment] 2020-10-08 13:34
> Linking libffi7 as libffi6 solved the problem for now. Not ideal tho...
> 
> https://stackoverflow.com/questions/61875869/ubuntu-20-04-upgrade-python-missing-libffi-so-6

After listed all possible references with ```find /usr/lib -name "libffi.so*"```, I used ```sudo ln -s /usr/lib/x86_64-linux-gnu/libffi.so.7 /usr/lib/x86_64-linux-gnu/libffi.so.6``` to fix the problem.

**Comment by TheRealChssAddct** [comment] 2020-12-26 21:09
This did not work for ubuntu 20.10 (groovy gorilla) even with linking from libffi.so.8. 
(it partially worked, getting past this error, but then gave a different error when loading the service.)

The following the instructions **did** work for me (originall from this comment [here](https://stackoverflow.com/questions/61875869/ubuntu-20-04-upgrade-python-missing-libffi-so-6/63329830#63329830).)

- **download** the 19.10 version of the package from here: [libffi6_3.2.1-8_amd64.deb](http://mirrors.kernel.org/ubuntu/pool/main/libf/libffi/libffi6_3.2.1-8_amd64.deb)

- **install** it with:
    `sudo apt install ./libffi6_3.2.1-8_amd64.deb`

**Comment by sgryphon** [comment] 2021-08-25 05:25
Appears to be a duplicate of https://github.com/microsoft/pgtoolsservice/issues/218 and should be closed.

They have the same error, a dialog that pops up on start and says "ImportError: libffi.so.6: cannot open shared object file: No such file or directory", then an error reported in the output section:

```
"It seems the debugger cannot resolve /opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/posixpath.py
This may make the debugger miss breakpoints in the standard library.
Related bug: https://bugs.python.org/issue1180193
... a stack trace ...
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
[Error - 12:57:17 PM] Connection to server got closed. Server will not be restarted."
```

The important bit is the missing "libffi.so.6"

There are many other duplicates (that should probably be closed as well)

https://github.com/microsoft/pgtoolsservice/issues/239
https://github.com/microsoft/pgtoolsservice/issues/251
https://github.com/microsoft/pgtoolsservice/issues/275
https://github.com/microsoft/pgtoolsservice/issues/279
https://github.com/microsoft/pgtoolsservice/issues/280
https://github.com/microsoft/pgtoolsservice/issues/282
https://github.com/microsoft/pgtoolsservice/issues/283

**Work around:**

So far, the workaround for some systems linking libffi.so.6 to version 7 seems to work:
 
```
sudo ln -s libffi.so.7 /usr/lib/x86_64-linux-gnu/libffi.so.6
```

The workaround does not work if you only have version 8, e.g. Ubuntu 20.10 -- it gets past the first error but then just fails. You can check which version you have via:

```
ls -la /usr/lib/x86_64-linux-gnu/libffi*
```

The other workaround is to directly install the version 6 libraries directly:

```
curl -o libffi6_3.2.1-8_amd64.deb http://mirrors.kernel.org/ubuntu/pool/main/libf/libffi/libffi6_3.2.1-8_amd64.deb
sudo apt install ./libffi6_3.2.1-8_amd64.deb
```

**Comment by nasc17** [comment] 2023-07-07 18:08
Issue has been addressed in our unstable release of PostgreSQL extension v0.4.2 using pgtoolsservice v1.8.0. We would appreciate your verification that it has been handled appropriately.

**Closed by nasc17** 2023-07-07 18:08 UTC
Labels: Release-v0.4, M2
