### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by DenisNovac** [microsoft/pgtoolsservice#239] opened 2020-05-22 08:14 UTC
Hi.

I am running Kubuntu 20. Azure Data Studio installed from deb.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/usr/local/lib/python3.6/dist-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "pgsqltoolsservice/pgtoolsservice_main.py", line 11, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ptvsd/__init__.py", line 17, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ptvsd/attach_server.py", line 35, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ptvsd/visualstudio_py_debugger.py", line 24, in <module>
  File "/usr/lib/python3.6/ctypes/__init__.py", line 7, in <module>
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
[Error - 1:11:10 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by stratosgear** [comment] 2020-05-26 18:26
Same here!

That path does **not** exist on my system!  Is that a virtualized internal path for Data Studio?


Running latest updated version of Arch.

```
$ uname -a
Linux serenity 5.6.14-arch1-1 #1 SMP PREEMPT Wed, 20 May 2020 20:43:19 +0000 x86_64 GNU/Linux
```

```
Version: 1.18.0
Commit: 2acd37a1b1cff34b64fbb4ea2d40715d7e2accac
Date: 2020-05-19T23:44:18.113Z
VS Code: 1.45.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.6.14-arch1-1
```

**Comment by yankyhoffman** [comment] 2020-05-28 15:51
Ubuntu 20.04 Gnome newest Azure Data Studio, same issue

**Comment by imjamesku** [comment] 2020-06-02 03:22
Running on Manjaro. Same issue

**Comment by Singha360** [comment] 2020-06-20 09:49
Ubuntu 20.04 comes with Python 3.8, not 3.6.

Is there any plan to resolve this issue?

**Comment by gschuager** [comment] 2020-07-03 20:04
This worked for me as a workaround on Kubuntu 20

```
sudo ln -s /usr/lib/x86_64-linux-gnu/libffi.so.7 /usr/lib/x86_64-linux-gnu/libffi.so.6
```

(based on https://stackoverflow.com/a/61876234/19716)

**Comment by bryannsi** [comment] 2020-07-25 23:20
The symbolic link proposed by @gschuager works for me on **Ubuntu 20.04.1 LTS** *Linux 5.4.0-42-generic x86_64*.

**Comment by yrcunha** [comment] 2020-07-29 19:44
Esse link não funcionou para mim. E não instala no sistema o libffi6

**Comment by ViniciusFXavier** [comment] 2020-09-09 18:40
> This worked for me as a workaround on Kubuntu 20
> 
> ```
> sudo ln -s /usr/lib/x86_64-linux-gnu/libffi.so.7 /usr/lib/x86_64-linux-gnu/libffi.so.6
> ```
> 
> (based on https://stackoverflow.com/a/61876234/19716)

This Works here. 
Ubuntu 20

**Comment by smbecker** [comment] 2020-11-10 19:41
> This worked for me as a workaround on Kubuntu 20
> 
> ```
> sudo ln -s /usr/lib/x86_64-linux-gnu/libffi.so.7 /usr/lib/x86_64-linux-gnu/libffi.so.6
> ```
> 
> (based on https://stackoverflow.com/a/61876234/19716)

This no longer works on Ubuntu 20.10. A better solution is to install `libffi.so.6` directly using [this method](https://stackoverflow.com/a/63329830).

**Comment by sgryphon** [comment] 2021-08-25 05:25
Appears to be a duplicate of https://github.com/microsoft/pgtoolsservice/issues/218 and should be closed.

They have the same error, a dialog that pops up on start and says "ImportError: libffi.so.6: cannot open shared object file: No such file or directory", then an error reported in the output section:

```
"It seems the debugger cannot resolve /opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/posixpath.py
This may make the debugger miss breakpoints in the standard library.
Related bug: https://bugs.python.org/issue1180193
... a stack trace ...
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
[Error - 12:57:17 PM] Connection to server got closed. Server will not be restarted."
```

The important bit is the missing "libffi.so.6"

There are many other duplicates (that should probably be closed as well)

https://github.com/microsoft/pgtoolsservice/issues/239
https://github.com/microsoft/pgtoolsservice/issues/251
https://github.com/microsoft/pgtoolsservice/issues/275
https://github.com/microsoft/pgtoolsservice/issues/279
https://github.com/microsoft/pgtoolsservice/issues/280
https://github.com/microsoft/pgtoolsservice/issues/282
https://github.com/microsoft/pgtoolsservice/issues/283

**Work around:**

So far, the workaround for some systems linking libffi.so.6 to version 7 seems to work:
 
```
sudo ln -s libffi.so.7 /usr/lib/x86_64-linux-gnu/libffi.so.6
```

The workaround does not work if you only have version 8, e.g. Ubuntu 20.10 -- it gets past the first error but then just fails. You can check which version you have via:

```
ls -la /usr/lib/x86_64-linux-gnu/libffi*
```

The other workaround is to directly install the version 6 libraries directly:

```
curl -o libffi6_3.2.1-8_amd64.deb http://mirrors.kernel.org/ubuntu/pool/main/libf/libffi/libffi6_3.2.1-8_amd64.deb
sudo apt install ./libffi6_3.2.1-8_amd64.deb
```

**Comment by foxx** [comment] 2022-01-16 18:47
Any chance of some feedback from Microsoft or maintainers on this one? It's been broken for quite some time and there's a lot of related issues.

**Comment by nasc17** [comment] 2023-07-07 18:09
Issue has been addressed in our unstable release of PostgreSQL extension v0.4.2 using pgtoolsservice v1.8.0. We would appreciate your verification that it has been handled appropriately.

**Closed by nasc17** 2023-07-07 18:09 UTC
Labels: Release-v0.4, M2
