### ISSUE TITLE
OSS DB Tools service component exited unexpectedelly using Azure on Ubuntu 18.04

### ISSUE THREAD

**Issue by anassis** [microsoft/pgtoolsservice#279] opened 2021-03-01 20:18 UTC
I have a problem to connect my postgreSQL database on Azure, on my Ubuntu 18.04 (Bionic Beaver). I have installed Docker version 20.10.4 and the last version of Azure. The error message is about: "OSS DB Tools service component exited unexpectedelly. Please restart Azure Data Studio". However, I've restarted, updated, upgraded, restarted again (even the PC!), and the error persists. Somebody could help me, please?

**Comment by arandilopez** [comment] 2021-03-02 20:13
Happens the same with Pop_Os 20.04 (Ubuntu 20.04)

```
It seems the debugger cannot resolve /opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/posixpath.py
This may make the debugger miss breakpoints in the standard library.
Related bug: https://bugs.python.org/issue1180193
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 37, in run
  File "ossdbtoolsservice/ossdbtoolsservice_main.py", line 11, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/ptvsd/__init__.py", line 13, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/ptvsd/_vendored/force_pydevd.py", line 37, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/ptvsd/_vendored/__init__.py", line 123, in preimport
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/importlib/__init__.py", line 126, in import_module
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/pydevd.py", line 31, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/_pydevd_bundle/pydevd_utils.py", line 8, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/ctypes/__init__.py", line 7, in <module>
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
[Error - 2:11:58 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by Datapipes** [comment] 2021-03-05 19:11
Me too. pulled the latest postgres container from dockerhub. Installed the postgres extension. same results as above

**Comment by anassis** [comment] 2021-03-05 20:16
My solution was installing a fresh 18.04 Ubuntu. After all, I have
installed Docker and Azure (.deb) with problems, But, on Ubuntu those
dependencies have been installed after Azure:

sudo apt-get install libxss1 sudo apt-get install libgconf-2-4 sudo apt-get
install libunwind8

Artur Neves De Assis
Doutor em Gestão Estratégica para a Sustentabilidade, UNAMA


Em sex., 5 de mar. de 2021 às 16:11, Datapipes <notifications@github.com>
escreveu:

**Comment by nogweii** [comment] 2021-04-06 22:06
I'm getting the same error, when attempting to install pgtoolsservice.

I'm running Arch Linux, and it ships a libffi package with an `.so` version of **7** -- e.g. the ffi library is located at `/usr/lib/libffi.so.7`. But the vendored python libraries are using FFI to look for version 6 of the library.

**Comment by sgryphon** [comment] 2021-08-25 05:25
Appears to be a duplicate of https://github.com/microsoft/pgtoolsservice/issues/218 and should be closed.

They have the same error, a dialog that pops up on start and says "ImportError: libffi.so.6: cannot open shared object file: No such file or directory", then an error reported in the output section:

```
"It seems the debugger cannot resolve /opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/posixpath.py
This may make the debugger miss breakpoints in the standard library.
Related bug: https://bugs.python.org/issue1180193
... a stack trace ...
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
[Error - 12:57:17 PM] Connection to server got closed. Server will not be restarted."
```

The important bit is the missing "libffi.so.6"

There are many other duplicates (that should probably be closed as well)

https://github.com/microsoft/pgtoolsservice/issues/239
https://github.com/microsoft/pgtoolsservice/issues/251
https://github.com/microsoft/pgtoolsservice/issues/275
https://github.com/microsoft/pgtoolsservice/issues/279
https://github.com/microsoft/pgtoolsservice/issues/280
https://github.com/microsoft/pgtoolsservice/issues/282
https://github.com/microsoft/pgtoolsservice/issues/283

**Work around:**

So far, the workaround for some systems linking libffi.so.6 to version 7 seems to work:
 
```
sudo ln -s libffi.so.7 /usr/lib/x86_64-linux-gnu/libffi.so.6
```

The workaround does not work if you only have version 8, e.g. Ubuntu 20.10 -- it gets past the first error but then just fails. You can check which version you have via:

```
ls -la /usr/lib/x86_64-linux-gnu/libffi*
```

The other workaround is to directly install the version 6 libraries directly:

```
curl -o libffi6_3.2.1-8_amd64.deb http://mirrors.kernel.org/ubuntu/pool/main/libf/libffi/libffi6_3.2.1-8_amd64.deb
sudo apt install ./libffi6_3.2.1-8_amd64.deb
```

**Comment by nasc17** [comment] 2023-07-07 18:09
Issue has been addressed in our unstable release of PostgreSQL extension v0.4.2 using pgtoolsservice v1.8.0. We would appreciate your verification that it has been handled appropriately.

**Closed by nasc17** 2023-07-07 18:09 UTC
